name = "service-manuals-pro"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"
pages_build_output_dir = ".open-next/assets"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[r2_buckets]]
binding = "DOCUMENTS_BUCKET"
bucket_name = "service-manuals-documents"
