name = "service-manuals-pro"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/assets"

[[r2_buckets]]
binding = "DOCUMENTS_BUCKET"
bucket_name = "service-manuals-documents"
